
package com.shaheen.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "UserControllerService", targetNamespace = "http://service.shaheen.com", wsdlLocation = "http://localhost:8088/Spring-jax-ws/remote/UserService?wsdl")
public class UserControllerService
    extends Service
{

    private final static URL USERCONTROLLERSERVICE_WSDL_LOCATION;
    private final static WebServiceException USERCONTROLLERSERVICE_EXCEPTION;
    private final static QName USERCONTROLLERSERVICE_QNAME = new QName("http://service.shaheen.com", "UserControllerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8088/Spring-jax-ws/remote/UserService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        USERCONTROLLERSERVICE_WSDL_LOCATION = url;
        USERCONTROLLERSERVICE_EXCEPTION = e;
    }

    public UserControllerService() {
        super(__getWsdlLocation(), USERCONTROLLERSERVICE_QNAME);
    }

    public UserControllerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), USERCONTROLLERSERVICE_QNAME, features);
    }

    public UserControllerService(URL wsdlLocation) {
        super(wsdlLocation, USERCONTROLLERSERVICE_QNAME);
    }

    public UserControllerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, USERCONTROLLERSERVICE_QNAME, features);
    }

    public UserControllerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UserControllerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UserService
     */
    @WebEndpoint(name = "UserServicePort")
    public UserService getUserServicePort() {
        return super.getPort(new QName("http://service.shaheen.com", "UserServicePort"), UserService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UserService
     */
    @WebEndpoint(name = "UserServicePort")
    public UserService getUserServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.shaheen.com", "UserServicePort"), UserService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (USERCONTROLLERSERVICE_EXCEPTION!= null) {
            throw USERCONTROLLERSERVICE_EXCEPTION;
        }
        return USERCONTROLLERSERVICE_WSDL_LOCATION;
    }

}
